repository:
  name: clickup-timer
  description: A tool for tracking time on ClickUp tasks
  topics: clickup,timer,time-tracking
  private: false
  has_issues: false
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: false
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: false
