name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: clickup-timer
          default-branch: main
  
  publish:
    runs-on: ${{ matrix.os }}
    needs: release
    if: ${{needs.release.outputs.release_created}}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        stage: [prod]

    steps:
      - uses: actions/checkout@v3

      - if: startsWith(matrix.os, 'ubuntu')
        name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libsndfile-dev

      - if: startsWith(matrix.os, 'windows')
        name: Install dependencies
        uses: microsoft/setup-msbuild@v1.3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'
          cache-dependency-path: |
            **/yarn.lock
            **/package-lock.json

      - name: Install Node dependencies
        run: yarn install --frozen-lockfile

      - name: Release (Ubuntu / Debian - x64)
        if: startsWith(matrix.os, 'ubuntu')
        run: yarn run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Release (Windows - x64)
        if: startsWith(matrix.os, 'windows')
        run: yarn run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release (MacOS - x64,arm64)
        if: startsWith(matrix.os, 'macos')
        run: yarn run publish --arch=x64,arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


